project_name: snazy
builds:
  - main: dummy.go
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    binary: snazy
    hooks:
      post: /bin/bash -c "install -m755 target/darwin_amd64/snazy/snazy dist/snazy_darwin_amd64_v1/snazy;install -m755 target/linux_amd64/snazy/snazy dist/snazy_linux_amd64_v1/snazy"
archives:
  - replacements:
      darwin: macOS
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - src: misc/completions/*
        dst: completions
        strip_parent: true
checksum:
  name_template: 'checksums.txt'

brews:
  - name: snazy
    tap:
      owner: chmouel
      name: snazy
    folder: Formula
    homepage: "https://github.com/chmouel/snazy"
    description: snazy  - a snazy json log viewer
    install: |
      bin.install "snazy" => "snazy"
      prefix.install_metafiles
      bash_completion.install "completions/snazy.bash"
      fish_completion.install "completions/snazy.fish"
      zsh_completion.install "completions/_snazy"
nfpms:
  - file_name_template: "snazy-{{.Version}}_{{.Os}}-{{.Arch}}"
    homepage: https://github.com/chmouel/snazy
    description: snazy  - a snazy json log viewer
    maintainer: Chmouel Boudjnah <chmouel@chmouel.com>
    license: Apache 2.0
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    replacements:
      amd64: 64bit
      386: 32bit
      arm: ARM
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^Brew formula update"
      - Merge pull request
      - Merge branch
      - go mod tidy
      - Update README.md

universal_binaries:
  - replace: true
    name_template: "snazy"

release:
  prerelease: true

aurs:
  - name: snazy-bin
    homepage: "https://github.com/chmouel/snazy"
    description: "Snazy - a snazy json log viewer"
    maintainers:
      - "Chmouel Boudjnah <chmouel@chmouel.com>"
    license: Apache 2.0
    private_key: "{{ .Env.AUR_PRIVATE_KEY }}"
    git_url: ssh://aur@aur.archlinux.org/snazy-bin.git
    package: |
      # bin
      install -Dm755 "./snazy" "${pkgdir}/usr/bin/snazy"

      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/snazy/LICENSE"

      # completions
      mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
      mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
      mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d/"

      install -Dm644 "completions/snazy.bash" "${pkgdir}/usr/share/bash-completion/completions/snazy"
      install -Dm644 "completions/snazy.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/snazy.fish"
      install -Dm644 "completions/_snazy" "${pkgdir}/usr/share/zsh/site-functions/_snazy"
