[package]
build = "build.rs"
authors = ["Chmouel Boudjnah <chmouel@chmouel.com>"]
categories = ["command-line-utilities"]
description = "snazy is a snazy json log viewer"
license = "MIT/Apache-2.0"
readme = "README.md"
name = "snazy"
version = "0.0.2"
edition = "2021"

[badges.appveyor]
repository = "chmouel/snazy"

[dependencies]
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
chrono = "0.4.19"
yansi = "0.5.1"
clap = { version = "3.1", features = ["derive", "cargo"] }
regex = "1.5.5"

[build-dependencies]
clap = { version = "3.1", features = ["cargo"] }
clap_complete = "3.1"
