[package]
# build = "build.rs"
authors = ["Chmouel Boudjnah <chmouel@chmouel.com>"]
categories = ["command-line-utilities"]
description = "snazy is a snazzy json log viewer"
license = "Apache-2.0"
readme = "README.md"
name = "snazy"
version = "0.50.0"
edition = "2021"
keywords = ["json", "log", "viewer"]

[badges.appveyor]
repository = "chmouel/snazy"

[dependencies]
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
chrono = { version = "0.4.24", default-features = false, features = ["clock"] }
yansi = "0.5.1"
clap = { version = "4", features = ["suggestions", "derive", "env"] }
regex = "1.8.0"
atty = "0.2.14"
tempfile = "3.4.0"
clap_complete = "4.1.6"
color-print = "0.3.4"
