[package]
# build = "build.rs"
authors = ["Chmouel Boudjnah <chmouel@chmouel.com>"]
categories = ["command-line-utilities"]
description = "snazy is a snazzy json log viewer"
license = "Apache-2.0"
readme = "README.md"
name = "snazy"
version = "0.52.1"
edition = "2021"
keywords = ["json", "log", "viewer"]

[badges.appveyor]
repository = "chmouel/snazy"

[dependencies]
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.108"
chrono = { version = "0.4.26", default-features = false, features = ["clock"] }
yansi = "0.5.1"
clap = { version = "4", features = ["suggestions", "derive", "env"] }
regex = "1.9.3"
tempfile = "3.7.1"
clap_complete = "4.3.2"
color-print = "0.3.4"
is-terminal = "0.4.9"
