[package]
# build = "build.rs"
authors = ["Chmouel Boudjnah <chmouel@chmouel.com>"]
categories = ["command-line-utilities"]
description = "snazy is a snazzy json log viewer"
license = "Apache-2.0"
readme = "README.md"
name = "snazy"
version = "0.50.0"
edition = "2021"
keywords = ["json", "log", "viewer"]

[badges.appveyor]
repository = "chmouel/snazy"

[dependencies]
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.89"
chrono = "0.4.23"
yansi = "0.5.1"
clap = { version = "4", features = ["suggestions", "derive", "env"] }
regex = "1.7.1"
atty = "0.2.14"
tempfile = "3.3.0"
clap_complete = "4.0.2"
