# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Snazy < Formula
  desc "snazy  - a snazy json log viewer"
  homepage "https://github.com/chmouel/snazy"
  version "0.0.2"

  on_macos do
    url "https://github.com/chmouel/snazy/releases/download/0.0.2/snazy_0.0.2_macOS_all.tar.gz"
    sha256 "79f6ada57e2eab617e9ddd1f2602de276dcec66e19b735d5b8c426f9ae3d1d0a"

    def install
      bin.install "snazy" => "snazy"
      prefix.install_metafiles
      bash_completion.install "completions/snazy.bash"
      fish_completion.install "completions/snazy.fish"
      zsh_completion.install "completions/_snazy"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/chmouel/snazy/releases/download/0.0.2/snazy_0.0.2_linux_amd64.tar.gz"
      sha256 "4435c7491f77a4bc186099c07b7453f7f38081b42bb24a1fa202cb484f1829f2"

      def install
        bin.install "snazy" => "snazy"
        prefix.install_metafiles
        bash_completion.install "completions/snazy.bash"
        fish_completion.install "completions/snazy.fish"
        zsh_completion.install "completions/_snazy"
      end
    end
  end
end
