# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Snazy < Formula
  desc "snazy - a snazzy json log viewer"
  homepage "https://github.com/chmouel/snazy"
  version "0.9.0"

  on_macos do
    url "https://github.com/chmouel/snazy/releases/download/0.9.0/snazy_0.9.0_macOS_all.tar.gz"
    sha256 "b73bc84d87cb70f00b685909ad57753729a9a9b8b91cc5ebe0bbf9dd180e8c31"

    def install
      bin.install "snazy" => "snazy"
      prefix.install_metafiles
      bash_completion.install "completions/snazy.bash"
      fish_completion.install "completions/snazy.fish"
      zsh_completion.install "completions/_snazy"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/chmouel/snazy/releases/download/0.9.0/snazy_0.9.0_linux_amd64.tar.gz"
      sha256 "a1aa6b70b00d61359d44033fcf9b4a04e75d7d1538fdb0e9944e0ac1e10b59e3"

      def install
        bin.install "snazy" => "snazy"
        prefix.install_metafiles
        bash_completion.install "completions/snazy.bash"
        fish_completion.install "completions/snazy.fish"
        zsh_completion.install "completions/_snazy"
      end
    end
  end
end
