name: goreleaser

on:
  push:
    # run only against tags
    tags:
      - '*'

permissions:
  contents: write
  # packages: write
  issues: write

jobs:
  build:
    # runs-on: ubuntu-latest
    name: ${{ matrix.job.os }} (${{ matrix.job.target }})
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - {os: ubuntu-latest, target: x86_64-unknown-linux-gnu}
          - {os: macos-latest, target: x86_64-apple-darwin}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fetch all tags
        run: git fetch --force --tags
      - name: Check that the Cargo.yaml has been updated with tag
        run: |
          if ! grep -E "version[ ]*=[ ]*.${GITHUB_REF#refs/tags/}." Cargo.toml; then
            echo "Cargo.toml version does not match tag, version in current Cargo.toml:"
            exit 1
          fi
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.job.target }}
      - uses: Swatinem/rust-cache@v2
      - name: Build on ${{ matrix.job.target }}
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=${{ matrix.job.target }}

      - uses: actions/upload-artifact@v3
        with:
          name: snazy-${{ matrix.job.target }}
          path: target/${{ matrix.job.target }}/release/snazy
  goreleaser:
    name: Goreleaser over Rust
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v3
        with:
          name: snazy-x86_64-unknown-linux-gnu
          path: target/linux_amd64/snazy
      - uses: actions/download-artifact@v3
        with:
          name: snazy-x86_64-apple-darwin
          path: target/darwin_amd64/snazy

      # - uses: mxschmitt/action-tmate@v3

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUR_PRIVATE_KEY: ${{ secrets.AUR_PRIVATE_KEY }}

      # - uses: katyo/publish-crates@v2
      #   with:
      #     registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
